inherit_gem:
  bixby: bixby_default.yml

AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  Exclude:
    - 'spec/internal_test_hyrax/**/*'
    - 'vendor/**/*'
    - 'config/**/*'
    - 'lib/generators/hyrax/autopopulation/install_generator.rb'

Metrics/BlockLength:
  Max: 80
  Exclude:
    - 'spec/**/*.rb'
    - 'lib/hyrax/autopopulation/engine.rb'

Metrics/MethodLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'hyrax-autopopulation.gemspec'
    - 'lib/hyrax/autopopulation/engine.rb'

Metrics/AbcSize:
  Exclude:
    - 'lib/hyrax/autopopulation/engine.rb'

RSpec/ExampleLength:
  Max: 25

Layout/LineLength:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/views/**/*'

Style/FrozenStringLiteralComment:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes
  Exclude:
    - 'config/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'app/bin/*'
    - '**/*.gemfile'
    - '**/*.gemspec'
    - '**/*.rake'
    - '**/*.ru'
    - '**/Gemfile'
    - '**/Rakefile'
    - 'spec/internal_test_hyku/**/*'

RSpec/LetSetup:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false


Naming/FileName:
  Exclude:
    - 'Gemfile'
    - 'hyrax-autopopulation.gemspec'
